# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import daemon_link_pb2 as daemon__link__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in daemon_link_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DaemonLinkStub(object):
    """DaemonLink is the custom gRPC control hub for the daemon link (HTTP/2).
    The daemon ALWAYS initiates streams (outbound-only), presenting a daemon
    access token in call metadata ("authorization: Bearer <jwt>"), validated by
    a server interceptor. Delivery guarantees (at-least-once + idempotency) are
    carried at the app layer via seq/ack fields, since gRPC won't redeliver
    across a reconnect.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Connect = channel.stream_stream(
                '/synapse.daemon.v1.DaemonLink/Connect',
                request_serializer=daemon__link__pb2.DaemonMessage.SerializeToString,
                response_deserializer=daemon__link__pb2.CloudMessage.FromString,
                _registered_method=True)
        self.IngestTelemetry = channel.stream_unary(
                '/synapse.daemon.v1.DaemonLink/IngestTelemetry',
                request_serializer=daemon__link__pb2.TelemetryFrame.SerializeToString,
                response_deserializer=daemon__link__pb2.TelemetryAck.FromString,
                _registered_method=True)


class DaemonLinkServicer(object):
    """DaemonLink is the custom gRPC control hub for the daemon link (HTTP/2).
    The daemon ALWAYS initiates streams (outbound-only), presenting a daemon
    access token in call metadata ("authorization: Bearer <jwt>"), validated by
    a server interceptor. Delivery guarantees (at-least-once + idempotency) are
    carried at the app layer via seq/ack fields, since gRPC won't redeliver
    across a reconnect.
    """

    def Connect(self, request_iterator, context):
        """Bidirectional control stream. The daemon pushes HITL requests, memory
        deltas, checkpoints, and run.reconcile up; the cloud pushes commands and
        HITL resolutions down. Daemon-initiated so the cloud reaches the daemon
        with no inbound port on the user's machine.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IngestTelemetry(self, request_iterator, context):
        """High-volume trace/metric firehose on its own HTTP/2 stream so telemetry
        cannot head-of-line-block control or HITL.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaemonLinkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Connect': grpc.stream_stream_rpc_method_handler(
                    servicer.Connect,
                    request_deserializer=daemon__link__pb2.DaemonMessage.FromString,
                    response_serializer=daemon__link__pb2.CloudMessage.SerializeToString,
            ),
            'IngestTelemetry': grpc.stream_unary_rpc_method_handler(
                    servicer.IngestTelemetry,
                    request_deserializer=daemon__link__pb2.TelemetryFrame.FromString,
                    response_serializer=daemon__link__pb2.TelemetryAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'synapse.daemon.v1.DaemonLink', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('synapse.daemon.v1.DaemonLink', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DaemonLink(object):
    """DaemonLink is the custom gRPC control hub for the daemon link (HTTP/2).
    The daemon ALWAYS initiates streams (outbound-only), presenting a daemon
    access token in call metadata ("authorization: Bearer <jwt>"), validated by
    a server interceptor. Delivery guarantees (at-least-once + idempotency) are
    carried at the app layer via seq/ack fields, since gRPC won't redeliver
    across a reconnect.
    """

    @staticmethod
    def Connect(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/synapse.daemon.v1.DaemonLink/Connect',
            daemon__link__pb2.DaemonMessage.SerializeToString,
            daemon__link__pb2.CloudMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IngestTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/synapse.daemon.v1.DaemonLink/IngestTelemetry',
            daemon__link__pb2.TelemetryFrame.SerializeToString,
            daemon__link__pb2.TelemetryAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
